<?php

namespace PointWeb\GuestBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GuestBookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuestBookRepository extends EntityRepository
{
}
