<?php

namespace PointWeb\FicheBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AutreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AutreRepository extends EntityRepository
{
}
