product:
    path:     /
    defaults: { _controller: "PointWebProductBundle:Default:index" }



product_show:
    path:     /{id}/show
    defaults: { _controller: PointWebProductBundle:Default:show }

