gallery:
    path:     /
    defaults: { _controller: "PointWebGalleryBundle:Default:index" }

gallery_show:
    path:     /{id}/show
    defaults: { _controller: "PointWebGalleryBundle:Default:show" }